return {
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      ChangeSkin=true,
      Digornot=false,
      DragonflyChest=false,
      Icebox=false,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-2710978964"]={
    configuration_options={
      atriumgate=20,
      average=false,
      bobbers=false,
      boss_modify=true,
      build=false,
      durable=0,
      gift=true,
      lightning=true,
      minmap=200,
      protect=1440,
      pullup=false,
      regularcleaning=-1,
      sleeper=true,
      start="love" 
    },
    enabled=true 
  },
  ["workshop-2753774601"]={
    configuration_options={
      [""]=0,
      button_can_be_moved=true,
      rb_cd=45,
      rb_penalty=false,
      rb_switch=true,
      tb_admin_delete=false,
      tb_announce=true,
      tb_consume=false,
      tb_switch=false 
    },
    enabled=true 
  },
  ["workshop-2847908822"]={
    configuration_options={
      [""]=false,
      ai1_switch=1,
      clean_day=false,
      compatible_switch=false,
      new_player_join_switch=2,
      perf_switch=true,
      performance_switch=true,
      performance_tips_switch=true,
      stack_dis=false 
    },
    enabled=true 
  },
  ["workshop-3355417965"]={ 
	  configuration_options={
      Auto_Clean_Item_time=2,
      Auto_Clean_Percent=60
    },
    enabled=true  },
  ["workshop-3096210166"]={
    configuration_options={
      can_drop_equip=true,
      equip=false,
      equip_drop=false,
      hoverer_text=true,
      key_config=120,
      medal_tr_num=true,
      monster=true,
      monster_day=false,
      monster_difficulty="2" 
    },
    enabled=true 
  },
  ["workshop-3120638435"]={ configuration_options={  }, enabled=true }
}